image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DEV_SERVER_HOST: 51.250.110.75
  DEV_SERVER_SSH_USER: tde
  DEV_APP_PORT: 9000
  DEV_ENDPOINT: http://$DEV_SERVER_HOST:$DEV_APP_PORT

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  tags:
    - docker
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "build/distributions/*.tar"

test:
  tags:
    - docker
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

deploy:
  tags:
    - shell
  stage: deploy
  dependencies:
    - build
  before_script:
    - tar xf build/distributions/Crowdfunding.tar --directory to_deploy
    - scp -o StrictHostKeyChecking=no ./to_deploy/* $SERVER_SSH_USER@$SERVER_HOST:~
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_SSH_USER@$SERVER_HOST "
      ./Crowdfunding/bin/Crowdfunding &

  environment: production
